version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: roda-admin
      POSTGRES_PASSWORD: roda-password
      POSTGRES_DB: rodadb
    networks:
      - backend
  core:
    build: ./roda_core
    command: ["./wait-for-it.sh", "db:5432", "--", "./start.sh"]
    volumes:
      - ./roda_core:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    stdin_open: true
    tty: true
  web:
    build: ./web
    command: ["yarn", "start"]
    volumes:
      - ./web:/code
    ports:
      - "3000:3000"
    depends_on:
      - core
    networks:
      - frontend
    stdin_open: true
    tty: true
networks:
  frontend:
  backend: