TYRE_POSITION_FRONT_LEFT = 'FL'
TYRE_POSITION_FRONT_RIGHT = 'FR'
TYRE_POSITION_REAR_LEFT = 'RL'
TYRE_POSITION_REAR_RIGHT = 'RR'

TYRE_POSITION_FRONT_LEFT_LABEL = 'Front Left'
TYRE_POSITION_FRONT_RIGHT_LABEL = 'Front Right'
TYRE_POSITION_REAR_LEFT_LABEL = 'Rear Left'
TYRE_POSITION_REAR_RIGHT_LABEL = 'Rear Right'

TYRE_POSITIONS = (
    (TYRE_POSITION_FRONT_LEFT, TYRE_POSITION_FRONT_LEFT_LABEL),
    (TYRE_POSITION_FRONT_RIGHT, TYRE_POSITION_FRONT_RIGHT_LABEL),
    (TYRE_POSITION_REAR_LEFT, TYRE_POSITION_REAR_LEFT_LABEL),
    (TYRE_POSITION_REAR_RIGHT, TYRE_POSITION_REAR_RIGHT_LABEL),
)

SAMPLE_DATA_PATH = 'resources/data_measurements_finals.csv'
FIELD_TIMESTAMP_FORMAT = '%Y-%m-%d %H:%M:%S'