# Generated by Django 2.0 on 2017-12-25 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TyreMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Timestamp')),
                ('position', models.CharField(choices=[('FL', 'Front Left'), ('FR', 'Front Right'), ('RL', 'Rear Left'), ('RR', 'Rear Right')], max_length=2)),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Pressure [bar]')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature [C˚]')),
                ('omega', models.FloatField(verbose_name='Angular Velocity')),
                ('speed', models.FloatField(verbose_name='Speed [km/h]')),
                ('car', models.CharField(max_length=255, verbose_name='Car')),
            ],
        ),
    ]
